// Chunk: Cart — Cart/checkout/orders/logistics pages

import type { PageLoadResult } from './types'
import { loadFromMap } from './types'

export const CHUNK_CART = new Set([
  'cart', 'checkout', 'orders', 'order-detail',
  'add-to-cart-confirm', 'add-to-cart-confirmation', 'bulk-order', 'bulk-order-form', 'quick-order', 'buy-now',
  'shipping-address', 'add-address', 'edit-address', 'delivery-method',
  'payment-method', 'add-payment-method', 'order-confirmation', 'order-summary', 'coupon-promo',
  'apply-credits', 'gift-card', 'order-invoice', 'split-payment', 'installment-payment',
  'track-order', 'my-orders', 'order-timeline', 'cancel-order',
  'return-request', 'return-detail', 'exchange-request', 'refund-status', 'refund-detail',
  'order-receipt', 'order-invoice-download',
  'dispute-center', 'dispute-detail', 'raise-complaint', 'order-feedback',
  'shipping-tracker', 'delivery-chat', 'delivery-confirmation', 'delivery-proof', 'missed-delivery',
  'reschedule-delivery', 'pickup-point', 'warehouse-locator', 'shipping-calculator', 'shipping-policies',
  'import-export-tracker', 'customs-clearance', 'freight-tracking',
  'review-order',
])

export async function loadChunkPage(pageId: string): Promise<PageLoadResult> {
  const loaders: Record<string, () => Promise<any>> = {
    'cart': () => import('@/components/pages/cart-page'),
    'checkout': () => import('@/components/pages/checkout-page'),
    'orders': () => import('@/components/pages/orders-page'),
    'my-orders': () => import('@/components/pages/orders-page'),
    'order-detail': () => import('@/components/pages/order-detail-page'),
    'add-to-cart-confirm': () => import('@/components/pages/add-to-cart-confirmation-page'),
    'add-to-cart-confirmation': () => import('@/components/pages/add-to-cart-confirmation-page'),
    'bulk-order': () => import('@/components/pages/bulk-order-form-page'),
    'bulk-order-form': () => import('@/components/pages/bulk-order-form-page'),
    'quick-order': () => import('@/components/pages/quick-order-page'),
    'buy-now': () => import('@/components/pages/buy-now-page'),
    'shipping-address': () => import('@/components/pages/shipping-address-page'),
    'add-address': () => import('@/components/pages/add-address-page'),
    'edit-address': () => import('@/components/pages/edit-address-page'),
    'delivery-method': () => import('@/components/pages/delivery-method-page'),
    'payment-method': () => import('@/components/pages/payment-method-page'),
    'add-payment-method': () => import('@/components/pages/add-payment-method-page'),
    'order-confirmation': () => import('@/components/pages/order-confirmation-page'),
    'order-summary': () => import('@/components/pages/order-summary-page'),
    'coupon-promo': () => import('@/components/pages/coupon-promo-page'),
    'apply-credits': () => import('@/components/pages/apply-credits-page'),
    'gift-card': () => import('@/components/pages/gift-card-page'),
    'order-invoice': () => import('@/components/pages/order-invoice-page'),
    'split-payment': () => import('@/components/pages/split-payment-page'),
    'installment-payment': () => import('@/components/pages/installment-payment-page'),
    'track-order': () => import('@/components/pages/track-order-page'),
    'order-timeline': () => import('@/components/pages/order-timeline-page'),
    'cancel-order': () => import('@/components/pages/cancel-order-page'),
    'return-request': () => import('@/components/pages/return-request-page'),
    'return-detail': () => import('@/components/pages/return-detail-page'),
    'exchange-request': () => import('@/components/pages/exchange-request-page'),
    'refund-status': () => import('@/components/pages/refund-status-page'),
    'refund-detail': () => import('@/components/pages/refund-detail-page'),
    'order-receipt': () => import('@/components/pages/order-receipt-page'),
    'order-invoice-download': () => import('@/components/pages/order-invoice-download-page'),
    'dispute-center': () => import('@/components/pages/dispute-center-page'),
    'dispute-detail': () => import('@/components/pages/dispute-detail-page'),
    'raise-complaint': () => import('@/components/pages/raise-complaint-page'),
    'order-feedback': () => import('@/components/pages/order-feedback-page'),
    'shipping-tracker': () => import('@/components/pages/shipping-tracker-page'),
    'delivery-chat': () => import('@/components/pages/delivery-chat-page'),
    'delivery-confirmation': () => import('@/components/pages/delivery-confirmation-page'),
    'delivery-proof': () => import('@/components/pages/delivery-proof-page'),
    'missed-delivery': () => import('@/components/pages/missed-delivery-page'),
    'reschedule-delivery': () => import('@/components/pages/reschedule-delivery-page'),
    'pickup-point': () => import('@/components/pages/pickup-point-page'),
    'warehouse-locator': () => import('@/components/pages/warehouse-locator-page'),
    'shipping-calculator': () => import('@/components/pages/shipping-calculator-page'),
    'shipping-policies': () => import('@/components/pages/shipping-policies-page'),
    'import-export-tracker': () => import('@/components/pages/import-export-tracker-page'),
    'customs-clearance': () => import('@/components/pages/customs-clearance-page'),
    'freight-tracking': () => import('@/components/pages/freight-tracking-page'),
  }
  return loadFromMap(loaders, pageId)
}
