// Chunk: Misc — Search, support, dashboards, notifications (2 real pages, others handled by generic components)

import type { PageLoadResult } from './types'
import { loadFromMap } from './types'

export const CHUNK_MISC = new Set([
  'admin-dashboard', 'buyer-dashboard',
  // Remaining pageIds resolve via generic components (component: null from loadFromMap)
  'buyer-orders', 'notifications', 'chat-list', 'chat-detail',
  'quote-request', 'coupons',
  'blog', 'blog-post', 'events',
  'browsing-history', 'coupons-offers', 'create-account', 'crop-image', 'crystal-clear', 'free-samples', 'market-trends', 'pdf-viewer', 'product-quick-view', 'promotion-banners', 'quick-view', 'reorder', 'team-management', 'wishlist-analytics', 'auction-page', 'b2b-services', 'bid-history', 'compliance-center', 'contract-management', 'digital-products', 'eco-friendly-products', 'enterprise', 'issue-tracker', 'price-list', 'quality-check', 'quick-links', 'seller-education',
  // Alias ids (deep-link compatibility) mapped to canonical components below
  'explore-page', 'faq-page', 'favorites-page', 'live-shopping-page', 'new-arrivals-page', 'notification-preferences-page', 'referral-program-page', 'rfq-list-page', 'seller-analytics-page', 'seller-badge-levels-page', 'seller-payouts-page', 'vip-benefits-page', 'wishlist-share-page', 'checkout-page', 'seller-dashboard-page', 'sitemap-page', 'trending-products-page', 'wishlist-page', 'category-directory', 'categories-page', 'checkout-success', 'compare-products', 'currency-settings', 'dashboard', 'department-store', 'disputes-page', 'download-app', 'exclusive-deal', 'feedback-page', 'flash-sales', 'gdpr', 'global-search', 'history-page', 'image-search-results', 'membership-trends', 'mobile-app', 'notification-center', 'onboarding-guide', 'order-tracking', 'orders-history', 'pickup-points', 'pricing', 'product-catalog', 'product-reviews-list', 'promotions-page', 'purchase-history', 'raise-dispute', 'rate-products', 'recently-viewed-products', 'register-seller', 'return-management', 'returns-exchange', 'seller-fulfillment', 'seller-onboarding', 'seller-sales-report', 'supplier-onboarding', 'supplier-verification-page', 'support-center', 'support-tickets', 'system-status', 'trade-assurance', 'track-consignment', 'trending-now', 'trust-center', 'upgrade-plan', 'verification-center', 'vip-club', 'voice-search-results', 'warehouse-management', 'warranty-claims', 'wholesale-account', 'wholesale-pricing', 'wishlist-shared', 'about-store', 'account-dashboard', 'account-overview', 'add-listing', 'all-orders', 'all-products', 'all-reviews', 'analytics-dashboard', 'approved-suppliers', 'auth-callback', 'become-a-seller', 'bulk-enquiry', 'business-directory', 'buyer-insights', 'career-page', 'catalog-management', 'contact-page', 'custom-orders', 'customer-support', 'dashboard-overview', 'delivery-options', 'discount-center', 'docs-page', 'draft-orders', 'email-preferences', 'emergency-support', 'featured-suppliers', 'fulfillment-center', 'flash-sale-page', 'global-search-page', 'helpdesk', 'import-products', 'inquiry-page', 'instant-chat', 'job-listings', 'join-seller', 'loyalty-program', 'manufacturing-partners', 'marketplace-news', 'member-area', 'merchant-dashboard', 'messaging-center', 'newsletter', 'offers-page', 'order-bulk-actions', 'order-management-page', 'pending-orders', 'product-upload', 'rating-page', 'report-issue-page', 'return-page', 'reviews-page', 'reward-points', 'rfp', 'sell-with-us', 'seller-center', 'seller-guidelines', 'seller-help', 'seller-home', 'seller-policy', 'seller-signup', 'seller-store-settings', 'seller-tools', 'shipping-info', 'shipping-zones', 'shop-page', 'size-chart', 'spin-wheel', 'store-analytics', 'store-management', 'store-page', 'store-settings', 'subscription-plans', 'supplier-center', 'supplier-listing', 'supplier-resources', 'support-ticket', 'system-health', 'top-suppliers', 'track-package', 'upcoming-products', 'vendor-registration', 'verified-suppliers', 'vip-program', 'wallet-page', 'wholesale-buying',
  // NOTE: search-*/help-center/faq/contact-us/live-chat/chatbot/ticket/report-*/
  // safety-center/community-guidelines/feedback were removed from this set —
  // they belong to chunk-search / chunk-support, whose loaders actually exist.
  // Listing them here made getChunkForPage() route them to 'misc', which has no
  // loader for them, so every such page showed "Page not found".
  // Notifications
  'notification-detail', 'push-notification-settings',
  'order-updates', 'promo-notifications',
  'price-drop-alerts', 'back-in-stock-alerts',
  'delivery-updates', 'notification-settings',
  'notification-sound-settings', 'notification-quiet-hours',
  'notification-categories', 'order-update-detail',
  'promo-detail', 'price-drop-detail',
  'back-in-stock-detail', 'delivery-update-detail',
  'notification-archive', 'notification-muted',
  'notification-filter', 'notification-search',
  'order-status-subscriptions', 'promo-preferences',
  'price-alert-create', 'stock-alert-create',
  'delivery-tracking-alerts', 'push-notification-per-channel',
  // Marketing & Promotions
  'my-coupons', 'earn-coupons', 'coupon-detail',
  'spin-win', 'spin-history',
  'daily-checkin', 'checkin-streak',
  'referral-program', 'referral-earnings',
  'affiliate-program', 'affiliate-dashboard',
  'loyalty-points', 'points-history',
  'redeem-points', 'points-detail',
  'vip-membership', 'membership-tiers',
  'vip-benefits', 'exclusive-deals',
  'group-buy', 'group-buy-detail',
  'live-shopping', 'live-shopping-detail',
  'mini-games', 'game-history',
  'exclusive-deal-detail',
  // Legal & Policy Core (195 - 207)
  'terms-of-service', 'terms', 'terms-and-conditions', 'buyer-terms', 'seller-terms', 'terms-faq', 'terms-history',
  'privacy-policy', 'privacy', 'data-collection', 'data-rights', 'data-deletion', 'privacy-faq',
  'return-policy', 'refund-policy', 'return-process', 'non-returnable', 'return-faq',
  'shipping-policy', 'delivery-policy', 'logistics-delivery-policy', 'shipping-policy-detail', 'domestic-shipping', 'international-shipping', 'shipping-faq',
  'payment-terms', 'payment-methods-detail', 'credit-terms', 'payment-faq',
  'wholesale-terms', 'wholesale-agreement', 'wholesale-faq',
  'cookie-policy', 'cookies', 'cookie-preferences', 'cookie-faq',
  'dmca-policy', 'dmca-submit', 'dmca-faq',
  'about-us', 'company-milestones', 'leadership-team', 'company-values',
  'careers-page', 'careers', 'job-detail', 'job-apply', 'career-benefits', 'career-culture', 'career-internships', 'career-life',
  'press-media', 'press-release-detail', 'media-kit',
  'investor-relations', 'annual-report', 'financial-filings', 'investor-presentation', 'investor-contact',
  'sitemap',
  // App-Level & Native Android (208 - 216)
  'app-settings', 'general-settings', 'app-general-settings', 'display-settings', 'network-settings', 'app-network-settings',
  'security-settings', 'app-security-settings', 'app-language-settings', 'data-sync',
  'storage-management', 'storage-breakdown', 'clear-storage', 'clear-data', 'offline-data-manager',
  'cache-settings', 'cache-stats', 'image-cache', 'purge-cache', 'clear-cache',
  'app-update', 'update-changelog', 'version-history', 'update-history', 'apk-download',
  'maintenance-mode', 'maintenance-schedule', 'service-status',
  'error-404', 'broken-link-report', 'page-suggestions',
  'error-500', 'error-boundary', 'server-diagnostics', 'crash-report',
  'offline-mode', 'offline-content', 'offline-catalogue', 'offline-sync-queue', 'sync-queue', 'offline-orders',
  'deep-link-handler', 'link-configuration', 'link-generator', 'link-analytics', 'qr-deeplink',
])

export async function loadChunkPage(pageId: string): Promise<PageLoadResult> {
  const loaders: Record<string, () => Promise<any>> = {
    'admin-dashboard': () => import('@/components/pages/admin-dashboard-page'),
    'admin-reports': () => import('@/components/pages/admin-reports-page'),
    'admin-moderation': () => import('@/components/pages/admin-reports-page'),
    'buyer-dashboard': () => import('@/components/pages/buyer-dashboard-page'),

    // Core Notifications Pages 171-178
    'notifications': () => import('@/components/pages/notifications-page'),
    'notification-detail': () => import('@/components/pages/notification-detail-page'),
    'push-notification-settings': () => import('@/components/pages/push-notification-settings-page'),
    'notification-settings': () => import('@/components/pages/push-notification-settings-page'),
    'order-updates': () => import('@/components/pages/order-updates-page'),
    'promo-notifications': () => import('@/components/pages/promo-notifications-page'),
    'price-drop-alerts': () => import('@/components/pages/price-drop-alerts-page'),
    'back-in-stock-alerts': () => import('@/components/pages/back-in-stock-alerts-page'),
    'delivery-updates': () => import('@/components/pages/delivery-updates-page'),

    // Notification Sub-pages
    'price-alert-create': () => import('@/components/pages/price-alert-create-page'),
    'stock-alert-create': () => import('@/components/pages/stock-alert-create-page'),
    'notification-archive': () => import('@/components/pages/notification-archive-page'),
    'notification-sound-settings': () => import('@/components/pages/notification-sound-settings-page'),
    'notification-quiet-hours': () => import('@/components/pages/notification-quiet-hours-page'),
    'notification-categories': () => import('@/components/pages/notification-categories-page'),
    'promo-preferences': () => import('@/components/pages/promo-preferences-page'),
    'delivery-tracking-alerts': () => import('@/components/pages/delivery-tracking-alerts-page'),
    'order-status-subscriptions': () => import('@/components/pages/order-status-subscriptions-page'),
    'push-notification-per-channel': () => import('@/components/pages/push-notification-per-channel-page'),
    'notification-filter': () => import('@/components/pages/notification-filter-page'),
    'notification-search': () => import('@/components/pages/notification-search-page'),
    'notification-muted': () => import('@/components/pages/notification-muted-page'),
    'order-update-detail': () => import('@/components/pages/order-update-detail-page'),
    'delivery-update-detail': () => import('@/components/pages/delivery-update-detail-page'),
    'promo-detail': () => import('@/components/pages/promo-detail-page'),
    'price-drop-detail': () => import('@/components/pages/price-drop-detail-page'),
    'back-in-stock-detail': () => import('@/components/pages/back-in-stock-detail-page'),

    // Marketing & Promotions Core (179 - 194)
    'coupons': () => import('@/components/pages/coupons-page'),
    'blog': () => import('@/components/pages/blog-page'),
    'blog-post': () => import('@/components/pages/blog-page'),
    'events': () => import('@/components/pages/events-page'),
    'browsing-history': () => import('@/components/pages/recently-viewed-page'),
    'coupons-offers': () => import('@/components/pages/coupons-page'),
    'create-account': () => import('@/components/pages/register-page'),
    'crop-image': () => import('@/components/pages/profile-photo-page'),
    'crystal-clear': () => import('@/components/pages/clear-storage-page'),
    'free-samples': () => import('@/components/pages/daily-deals-page'),
    'market-trends': () => import('@/components/pages/blog-page'),
    'pdf-viewer': () => import('@/components/pages/media-kit-page'),
    'product-quick-view': () => import('@/components/pages/product-detail-page'),
    'promotion-banners': () => import('@/components/pages/daily-deals-page'),
    'quick-view': () => import('@/components/pages/product-detail-page'),
    'reorder': () => import('@/components/pages/orders-page'),
    'team-management': () => import('@/components/pages/staff-profile-page'),
    'wishlist-analytics': () => import('@/components/pages/wishlist-page'),
    'auction-page': () => import('@/components/pages/exclusive-deals-page'),
    'b2b-services': () => import('@/components/pages/explore-page'),
    'bid-history': () => import('@/components/pages/exclusive-deals-page'),
    'compliance-center': () => import('@/components/pages/buyer-protection-policy-page'),
    'contract-management': () => import('@/components/pages/wholesale-agreement-page'),
    'digital-products': () => import('@/components/pages/category-browser-page'),
    'eco-friendly-products': () => import('@/components/pages/category-browser-page'),
    'enterprise': () => import('@/components/pages/register-buyer-page'),
    'issue-tracker': () => import('@/components/pages/help-center-page'),
    'price-list': () => import('@/components/pages/bulk-pricing-page'),
    'quality-check': () => import('@/components/pages/buyer-protection-policy-page'),
    'quick-links': () => import('@/components/pages/sitemap-page'),
    'seller-education': () => import('@/components/pages/seller-verification-guide-page'),
    'explore-page': () => import('@/components/pages/explore-page'),
    'faq-page': () => import('@/components/pages/faq-page'),
    'favorites-page': () => import('@/components/pages/favorites-page'),
    'live-shopping-page': () => import('@/components/pages/live-shopping-page'),
    'new-arrivals-page': () => import('@/components/pages/new-arrivals-page'),
    'notification-preferences-page': () => import('@/components/pages/notification-preferences-page'),
    'referral-program-page': () => import('@/components/pages/referral-program-page'),
    'rfq-list-page': () => import('@/components/pages/rfq-list-page'),
    'seller-analytics-page': () => import('@/components/pages/seller-analytics-page'),
    'seller-badge-levels-page': () => import('@/components/pages/seller-badge-levels-page'),
    'seller-payouts-page': () => import('@/components/pages/seller-payouts-page'),
    'vip-benefits-page': () => import('@/components/pages/vip-benefits-page'),
    'wishlist-share-page': () => import('@/components/pages/wishlist-share-page'),
    'checkout-page': () => import('@/components/pages/checkout-page'),
    'seller-dashboard-page': () => import('@/components/pages/seller-dashboard-page'),
    'sitemap-page': () => import('@/components/pages/sitemap-page'),
    'trending-products-page': () => import('@/components/pages/trending-products-page'),
    'wishlist-page': () => import('@/components/pages/wishlist-page'),
    'category-directory': () => import('@/components/pages/category-navigation-page'),
    'categories-page': () => import('@/components/pages/category-browser-page'),
    'checkout-success': () => import('@/components/pages/order-confirmation-page'),
    'compare-products': () => import('@/components/pages/product-comparison-page'),
    'currency-settings': () => import('@/components/pages/language-settings-page'),
    'dashboard': () => import('@/components/pages/buyer-dashboard-page'),
    'department-store': () => import('@/components/pages/category-browser-page'),
    'disputes-page': () => import('@/components/pages/dispute-center-page'),
    'download-app': () => import('@/components/pages/apk-download-page'),
    'exclusive-deal': () => import('@/components/pages/exclusive-deals-page'),
    'feedback-page': () => import('@/components/pages/feedback-suggestions-page'),
    'flash-sales': () => import('@/components/pages/flash-deals-page'),
    'gdpr': () => import('@/components/pages/data-rights-page'),
    'global-search': () => import('@/components/pages/search-home-page'),
    'history-page': () => import('@/components/pages/recently-viewed-page'),
    'image-search-results': () => import('@/components/pages/image-search-page'),
    'membership-trends': () => import('@/components/pages/membership-tiers-page'),
    'mobile-app': () => import('@/components/pages/apk-download-page'),
    'notification-center': () => import('@/components/pages/notifications-page'),
    'onboarding-guide': () => import('@/components/pages/welcome-page'),
    'order-tracking': () => import('@/components/pages/track-order-page'),
    'orders-history': () => import('@/components/pages/orders-page'),
    'pickup-points': () => import('@/components/pages/pickup-point-page'),
    'pricing': () => import('@/components/pages/bulk-pricing-page'),
    'product-catalog': () => import('@/components/pages/wholesale-catalog-page'),
    'product-reviews-list': () => import('@/components/pages/product-reviews-page'),
    'promotions-page': () => import('@/components/pages/daily-deals-page'),
    'purchase-history': () => import('@/components/pages/orders-page'),
    'raise-dispute': () => import('@/components/pages/raise-complaint-page'),
    'rate-products': () => import('@/components/pages/write-review-page'),
    'recently-viewed-products': () => import('@/components/pages/recently-viewed-page'),
    'register-seller': () => import('@/components/pages/register-supplier-page'),
    'return-management': () => import('@/components/pages/return-request-page'),
    'returns-exchange': () => import('@/components/pages/return-request-page'),
    'seller-fulfillment': () => import('@/components/pages/seller-order-fulfillment-page'),
    'seller-onboarding': () => import('@/components/pages/register-supplier-page'),
    'seller-sales-report': () => import('@/components/pages/seller-analytics-page'),
    'supplier-onboarding': () => import('@/components/pages/register-supplier-page'),
    'supplier-verification-page': () => import('@/components/pages/seller-verification-page'),
    'support-center': () => import('@/components/pages/help-center-page'),
    'support-tickets': () => import('@/components/pages/help-center-page'),
    'system-status': () => import('@/components/pages/service-status-page'),
    'trade-assurance': () => import('@/components/pages/buyer-protection-policy-page'),
    'track-consignment': () => import('@/components/pages/track-order-page'),
    'trending-now': () => import('@/components/pages/trending-products-page'),
    'trust-center': () => import('@/components/pages/safety-center-page'),
    'upgrade-plan': () => import('@/components/pages/membership-tiers-page'),
    'verification-center': () => import('@/components/pages/seller-verification-page'),
    'vip-club': () => import('@/components/pages/vip-membership-page'),
    'voice-search-results': () => import('@/components/pages/voice-search-page'),
    'warehouse-management': () => import('@/components/pages/inventory-management-page'),
    'warranty-claims': () => import('@/components/pages/return-request-page'),
    'wholesale-account': () => import('@/components/pages/register-buyer-page'),
    'wholesale-pricing': () => import('@/components/pages/bulk-pricing-page'),
    'wishlist-shared': () => import('@/components/pages/shared-wishlist-page'),
    'about-store': () => import('@/components/pages/seller-storefront-page'),
    'account-dashboard': () => import('@/components/pages/buyer-dashboard-page'),
    'account-overview': () => import('@/components/pages/account-settings-page'),
    'add-listing': () => import('@/components/pages/seller-add-product-page'),
    'all-orders': () => import('@/components/pages/orders-page'),
    'all-products': () => import('@/components/pages/supplier-products-page'),
    'all-reviews': () => import('@/components/pages/product-reviews-page'),
    'analytics-dashboard': () => import('@/components/pages/seller-analytics-page'),
    'approved-suppliers': () => import('@/components/pages/suppliers-directory-page'),
    'auth-callback': () => import('@/components/pages/login-page'),
    'become-a-seller': () => import('@/components/pages/register-supplier-page'),
    'bulk-enquiry': () => import('@/components/pages/bulk-order-form-page'),
    'business-directory': () => import('@/components/pages/suppliers-directory-page'),
    'buyer-insights': () => import('@/components/pages/buyer-dashboard-page'),
    'career-page': () => import('@/components/pages/careers-page'),
    'catalog-management': () => import('@/components/pages/product-listings-manager-page'),
    'contact-page': () => import('@/components/pages/contact-us-page'),
    'custom-orders': () => import('@/components/pages/bulk-order-form-page'),
    'customer-support': () => import('@/components/pages/help-center-page'),
    'dashboard-overview': () => import('@/components/pages/buyer-dashboard-page'),
    'delivery-options': () => import('@/components/pages/delivery-method-page'),
    'discount-center': () => import('@/components/pages/clearance-sale-page'),
    'docs-page': () => import('@/components/pages/docs-browser-page'),
    'draft-orders': () => import('@/components/pages/orders-page'),
    'email-preferences': () => import('@/components/pages/notification-preferences-page'),
    'emergency-support': () => import('@/components/pages/help-center-page'),
    'featured-suppliers': () => import('@/components/pages/suppliers-directory-page'),
    'fulfillment-center': () => import('@/components/pages/warehouse-locator-page'),
    'flash-sale-page': () => import('@/components/pages/flash-deals-page'),
    'global-search-page': () => import('@/components/pages/search-home-page'),
    'helpdesk': () => import('@/components/pages/help-center-page'),
    'import-products': () => import('@/components/pages/seller-add-product-page'),
    'inquiry-page': () => import('@/components/pages/contact-us-page'),
    'instant-chat': () => import('@/components/pages/live-chat-page'),
    'job-listings': () => import('@/components/pages/careers-page'),
    'join-seller': () => import('@/components/pages/register-supplier-page'),
    'loyalty-program': () => import('@/components/pages/loyalty-points-page'),
    'manufacturing-partners': () => import('@/components/pages/suppliers-directory-page'),
    'marketplace-news': () => import('@/components/pages/blog-page'),
    'member-area': () => import('@/components/pages/loyalty-points-page'),
    'merchant-dashboard': () => import('@/components/pages/seller-dashboard-page'),
    'messaging-center': () => import('@/components/pages/live-chat-page'),
    'newsletter': () => import('@/components/pages/promo-notifications-page'),
    'offers-page': () => import('@/components/pages/daily-deals-page'),
    'order-bulk-actions': () => import('@/components/pages/orders-page'),
    'order-management-page': () => import('@/components/pages/orders-page'),
    'pending-orders': () => import('@/components/pages/orders-page'),
    'product-upload': () => import('@/components/pages/seller-add-product-page'),
    'rating-page': () => import('@/components/pages/write-review-page'),
    'report-issue-page': () => import('@/components/pages/report-problem-page'),
    'return-page': () => import('@/components/pages/return-request-page'),
    'reviews-page': () => import('@/components/pages/product-reviews-page'),
    'reward-points': () => import('@/components/pages/loyalty-points-page'),
    'rfp': () => import('@/components/pages/rfq-list-page'),
    'sell-with-us': () => import('@/components/pages/register-supplier-page'),
    'seller-center': () => import('@/components/pages/seller-dashboard-page'),
    'seller-guidelines': () => import('@/components/pages/community-guidelines-page'),
    'seller-help': () => import('@/components/pages/help-center-page'),
    'seller-home': () => import('@/components/pages/seller-dashboard-page'),
    'seller-policy': () => import('@/components/pages/seller-terms-page'),
    'seller-signup': () => import('@/components/pages/register-supplier-page'),
    'seller-store-settings': () => import('@/components/pages/account-settings-page'),
    'seller-tools': () => import('@/components/pages/seller-quick-actions-page'),
    'shipping-info': () => import('@/components/pages/domestic-shipping-page'),
    'shipping-zones': () => import('@/components/pages/shipping-zone-editor-page'),
    'shop-page': () => import('@/components/pages/category-browser-page'),
    'size-chart': () => import('@/components/pages/size-guide-page'),
    'spin-wheel': () => import('@/components/pages/mini-games-page'),
    'store-analytics': () => import('@/components/pages/seller-analytics-page'),
    'store-management': () => import('@/components/pages/store-customization-page'),
    'store-page': () => import('@/components/pages/seller-storefront-page'),
    'store-settings': () => import('@/components/pages/store-customization-page'),
    'subscription-plans': () => import('@/components/pages/membership-tiers-page'),
    'supplier-center': () => import('@/components/pages/supplier-dashboard-page'),
    'supplier-listing': () => import('@/components/pages/supplier-products-page'),
    'supplier-resources': () => import('@/components/pages/register-supplier-page'),
    'support-ticket': () => import('@/components/pages/ticket-detail-page'),
    'system-health': () => import('@/components/pages/service-status-page'),
    'top-suppliers': () => import('@/components/pages/suppliers-directory-page'),
    'track-package': () => import('@/components/pages/track-order-page'),
    'upcoming-products': () => import('@/components/pages/new-arrivals-page'),
    'vendor-registration': () => import('@/components/pages/register-supplier-page'),
    'verified-suppliers': () => import('@/components/pages/suppliers-directory-page'),
    'vip-program': () => import('@/components/pages/vip-membership-page'),
    'wallet-page': () => import('@/components/pages/my-wallet-page'),
    'wholesale-buying': () => import('@/components/pages/wholesale-catalog-page'),
    'my-coupons': () => import('@/components/pages/my-coupons-page'),
    'earn-coupons': () => import('@/components/pages/earn-coupons-page'),
    'spin-win': () => import('@/components/pages/spin-win-page'),
    'daily-checkin': () => import('@/components/pages/daily-checkin-page'),
    'referral-program': () => import('@/components/pages/referral-program-page'),
    'affiliate-program': () => import('@/components/pages/affiliate-program-page'),
    'loyalty-points': () => import('@/components/pages/loyalty-points-page'),
    'points-history': () => import('@/components/pages/points-history-page'),
    'redeem-points': () => import('@/components/pages/redeem-points-page'),
    'vip-membership': () => import('@/components/pages/vip-membership-page'),
    'membership-tiers': () => import('@/components/pages/membership-tiers-page'),
    'exclusive-deals': () => import('@/components/pages/exclusive-deals-page'),
    'group-buy': () => import('@/components/pages/group-buy-page'),
    'live-shopping': () => import('@/components/pages/live-shopping-page'),
    'mini-games': () => import('@/components/pages/mini-games-page'),

    // Marketing Sub-pages
    'coupon-detail': () => import('@/components/pages/coupon-detail-page'),
    'spin-history': () => import('@/components/pages/spin-history-page'),
    'checkin-streak': () => import('@/components/pages/checkin-streak-page'),
    'referral-earnings': () => import('@/components/pages/referral-earnings-page'),
    'affiliate-dashboard': () => import('@/components/pages/affiliate-dashboard-page'),
    'points-detail': () => import('@/components/pages/points-detail-page'),
    'vip-benefits': () => import('@/components/pages/vip-benefits-page'),
    'exclusive-deal-detail': () => import('@/components/pages/exclusive-deal-detail-page'),
    'group-buy-detail': () => import('@/components/pages/group-buy-detail-page'),
    'live-shopping-detail': () => import('@/components/pages/live-shopping-detail-page'),
    'game-history': () => import('@/components/pages/game-history-page'),

    // Legal & Policy Core (195 - 207)
    'terms-of-service': () => import('@/components/pages/terms-of-service-page'),
    'terms': () => import('@/components/pages/terms-of-service-page'),
    'terms-and-conditions': () => import('@/components/pages/terms-of-service-page'),
    'privacy-policy': () => import('@/components/pages/privacy-policy-page'),
    'privacy': () => import('@/components/pages/privacy-policy-page'),
    'return-policy': () => import('@/components/pages/return-policy-page'),
    'refund-policy': () => import('@/components/pages/return-policy-page'),
    'shipping-policy': () => import('@/components/pages/shipping-policy-page'),
    'delivery-policy': () => import('@/components/pages/shipping-policy-page'),
    'logistics-delivery-policy': () => import('@/components/pages/shipping-policy-page'),
    'payment-terms': () => import('@/components/pages/payment-terms-page'),
    'wholesale-terms': () => import('@/components/pages/wholesale-terms-page'),
    'cookie-policy': () => import('@/components/pages/cookie-policy-page'),
    'cookies': () => import('@/components/pages/cookie-policy-page'),
    'dmca-policy': () => import('@/components/pages/dmca-policy-page'),
    'about-us': () => import('@/components/pages/about-us-page'),
    'careers-page': () => import('@/components/pages/careers-page'),
    'careers': () => import('@/components/pages/careers-page'),
    'press-media': () => import('@/components/pages/press-media-page'),
    'investor-relations': () => import('@/components/pages/investor-relations-page'),
    'sitemap': () => import('@/components/pages/sitemap-page'),

    // Legal & Policy Sub-pages
    'buyer-terms': () => import('@/components/pages/buyer-terms-page'),
    'seller-terms': () => import('@/components/pages/seller-terms-page'),
    'terms-faq': () => import('@/components/pages/terms-faq-page'),
    'terms-history': () => import('@/components/pages/terms-history-page'),
    'data-collection': () => import('@/components/pages/data-collection-page'),
    'data-rights': () => import('@/components/pages/data-rights-page'),
    'data-deletion': () => import('@/components/pages/data-deletion-page'),
    'privacy-faq': () => import('@/components/pages/privacy-faq-page'),
    'cookie-preferences': () => import('@/components/pages/cookie-preferences-page'),
    'cookie-faq': () => import('@/components/pages/cookie-faq-page'),
    'return-process': () => import('@/components/pages/return-process-page'),
    'non-returnable': () => import('@/components/pages/non-returnable-page'),
    'return-faq': () => import('@/components/pages/return-faq-page'),
    'domestic-shipping': () => import('@/components/pages/domestic-shipping-page'),
    'international-shipping': () => import('@/components/pages/international-shipping-page'),
    'shipping-faq': () => import('@/components/pages/shipping-faq-page'),
    'payment-methods-detail': () => import('@/components/pages/payment-methods-detail-page'),
    'credit-terms': () => import('@/components/pages/credit-terms-page'),
    'payment-faq': () => import('@/components/pages/payment-faq-page'),
    'wholesale-agreement': () => import('@/components/pages/wholesale-agreement-page'),
    'wholesale-faq': () => import('@/components/pages/wholesale-faq-page'),
    'dmca-submit': () => import('@/components/pages/dmca-submit-page'),
    'dmca-faq': () => import('@/components/pages/dmca-faq-page'),
    'job-detail': () => import('@/components/pages/job-detail-page'),
    'job-apply': () => import('@/components/pages/job-apply-page'),
    'career-benefits': () => import('@/components/pages/career-benefits-page'),
    'career-culture': () => import('@/components/pages/career-culture-page'),
    'career-internships': () => import('@/components/pages/career-culture-page'),
    'career-life': () => import('@/components/pages/career-culture-page'),
    'press-release-detail': () => import('@/components/pages/press-release-detail-page'),
    'media-kit': () => import('@/components/pages/media-kit-page'),
    'annual-report': () => import('@/components/pages/annual-report-page'),
    'financial-filings': () => import('@/components/pages/financial-filings-page'),
    'investor-presentation': () => import('@/components/pages/investor-presentation-page'),
    'investor-contact': () => import('@/components/pages/investor-contact-page'),
    'company-milestones': () => import('@/components/pages/company-milestones-page'),
    'leadership-team': () => import('@/components/pages/leadership-team-page'),
    'company-values': () => import('@/components/pages/company-values-page'),

    // App-Level & Native Android Engine (208 - 216 + Sub-tools)
    'app-settings': () => import('@/components/pages/app-settings-page'),
    'general-settings': () => import('@/components/pages/app-general-settings-page'),
    'app-general-settings': () => import('@/components/pages/app-general-settings-page'),
    'app-network-settings': () => import('@/components/pages/app-network-settings-page'),
    'network-settings': () => import('@/components/pages/app-network-settings-page'),
    'security-settings': () => import('@/components/pages/app-security-settings-page'),
    'app-security-settings': () => import('@/components/pages/app-security-settings-page'),
    'app-language-settings': () => import('@/components/pages/app-language-settings-page'),

    'storage-management': () => import('@/components/pages/storage-management-page'),
    'storage-breakdown': () => import('@/components/pages/storage-breakdown-page'),
    'clear-storage': () => import('@/components/pages/clear-storage-page'),
    'clear-data': () => import('@/components/pages/clear-storage-page'),
    'offline-data-manager': () => import('@/components/pages/offline-data-manager-page'),

    'cache-settings': () => import('@/components/pages/cache-settings-page'),
    'cache-stats': () => import('@/components/pages/cache-stats-page'),
    'image-cache': () => import('@/components/pages/image-cache-page'),
    'purge-cache': () => import('@/components/pages/purge-cache-page'),
    'clear-cache': () => import('@/components/pages/purge-cache-page'),

    'app-update': () => import('@/components/pages/app-update-page'),
    'update-changelog': () => import('@/components/pages/update-changelog-page'),
    'version-history': () => import('@/components/pages/version-history-page'),
    'update-history': () => import('@/components/pages/version-history-page'),
    'apk-download': () => import('@/components/pages/apk-download-page'),

    'maintenance-mode': () => import('@/components/pages/maintenance-mode-page'),
    'maintenance-schedule': () => import('@/components/pages/maintenance-schedule-page'),
    'service-status': () => import('@/components/pages/service-status-page'),

    'error-404': () => import('@/components/pages/error-404-page'),
    'broken-link-report': () => import('@/components/pages/broken-link-report-page'),
    'page-suggestions': () => import('@/components/pages/page-suggestions-page'),

    'error-500': () => import('@/components/pages/error-500-page'),
    'error-boundary': () => import('@/components/pages/error-500-page'),
    'server-diagnostics': () => import('@/components/pages/server-diagnostics-page'),
    'crash-report': () => import('@/components/pages/crash-report-page'),

    'offline-mode': () => import('@/components/pages/offline-mode-page'),
    'offline-content': () => import('@/components/pages/offline-mode-page'),
    'offline-catalogue': () => import('@/components/pages/offline-catalogue-page'),
    'offline-sync-queue': () => import('@/components/pages/offline-sync-queue-page'),
    'sync-queue': () => import('@/components/pages/offline-sync-queue-page'),
    'offline-orders': () => import('@/components/pages/offline-orders-page'),

    'deep-link-handler': () => import('@/components/pages/deep-link-handler-page'),
    'link-configuration': () => import('@/components/pages/deep-link-handler-page'),
    'link-generator': () => import('@/components/pages/link-generator-page'),
    'link-analytics': () => import('@/components/pages/link-analytics-page'),
    'qr-deeplink': () => import('@/components/pages/qr-deeplink-page'),
  }
  return loadFromMap(loaders, pageId)
}
